language: scala
# Trusty VM has 1.8u101
# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-243534696
dist: trusty
sudo: false
group: beta
jdk:
  - oraclejdk8
script:
  - framework/bin/travis
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
  # Delete any SBT lock files
  - find $HOME/.sbt -name "*.lock" -delete
